created an MVC for getting review info by ID
JamesATeasdale/be-nc-games pull request #3
Opened 2023-03-27 14:04 UTC by JamesATeasdale

2023-03-27 14:25 UTC, B7Bprog requested changes
Please read my comment and add the missing test. After it's done, please send us a quick pull request with it.

2023-03-27 14:25 UTC, B7Bprog commented on __tests__/app.test.js
> +	});
Please include a test for a 400, bad request, when the id is the wrong data type, for example a string. (/api/reviews/banana). You can check the psql error code for that and reject the promise based on that one.

2023-03-27 15:18 UTC, callumu21 approved these changes
Nice to see some newer syntax in use here (async, try/catch, ternary operators)! I've left some comments that should be addressed before you merge:

1. Amend app.use to not take a path as its initial argument
2. You should handle the rejection of your db.query in the model when there are no reviews, rather than the controller.

2023-03-27 15:18 UTC, callumu21 commented on controllers/app.controller.js
> +		review.rowCount === 0
This logic should be handled in the model when we choose whether to return the data or a rejected Promise.

2023-03-27 15:18 UTC, callumu21 commented on app.js
> +app.use("/", badDataType);
app.use just needs an error-handling middleware function as its argument, not a path as well.

2023-03-28 09:45 UTC, HeatherEver approved these changes
Nice work here! The only thing i would say is that i see you've used `async...await` in one controller and `.then promises` in another - i would say stick to one or the other in the same project just for consistency purposes

2023-03-28 09:51 UTC, merged